name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Java 17
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Step 3: Build with Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Step 4: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 5: Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 6: Build Docker Image
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hostel-app:latest .

    # Step 7: Push Docker Image
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/hostel-app:latest

    # Step 8: Deployment Success Message
    - name: Deployment Completed
      run: echo "Application Successfully Deployed to Docker Hub!"
